### ISSUE TITLE
Connecting to proxy fails, unless I use port forwarding

### ISSUE THREAD

**Issue by sc0ttkclark** [ericmann/openconnect-vm#7]
If I try to connect to my proxy via `openconnect`, it fails. If I go into the Virtualbox network settings for that vagrant box, and add the port forwarding as follows -- it works:

  1080 (guest) => 10800 (host)
    22 (guest) => 2222 (host)
  2080 (guest) => 20800 (host)

So then when I connect the proxy settings, I use localhost : 1080 for SOCKS and it's working fine. Not sure what's up there, or what caused that. Posting this here for a paper trail :)

**Comment by sc0ttkclark** [comment]
Quick solution to the port forwarding to keep the settings each up/halt, add `Customfile` to the root of the openconnect vagrant files (where `Vagrantfile` is) and add these two lines:

```
config.vm.network "forwarded_port", guest: 1080, host: 10800
config.vm.network "forwarded_port", guest: 2080, host: 20800
```

**Comment by ericmann** [comment]
The Customfile approach is a solid one for now. A couple of thoughts here:
1. Not ever Vagrant VM provider currently supports port forwarding, so unless we wrap this in an `if Virtualbox` conditional, I don't want to pull it into core.
2. If we _do_ enable forwarding by default, perhaps we should forward the stock ports (i.e. 1080=>1080) instead of aliases?

**Comment by ericmann** [comment]
Closing for now since we have a valid workaround (Customfile).
